name: Build and release

on:
  push:
    branches:
      - main
    paths:
      - '**.rs'
      - 'Cargo.lock'
      - 'Cargo.toml'
    tags-ignore:
      - dev-build

env:
  dev_tag: dev-build

jobs:
  build:
    uses: ./.github/workflows/build_artifacts.yml
  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: Downloads artifacts
        uses: actions/download-artifact@v3
        with:
          path: bin
      - name: Create pre-release
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          # body_path: ${{ github.workspace }}/CHANGELOG.md
          files: bin/*/rusty-autoclicker-*
          prerelease: false
